name: ROS 2 CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop python3-colcon-common-extensions

    - name: Setup colcon
      run: |
        source /opt/ros/humble/setup.bash
        sudo apt install -y python3-vcstool python3-pip
        python3 -m pip install -U vcstool

    - name: Install dependencies
      run: |
        sudo apt update
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
      working-directory: .

    - name: Build
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install
      working-directory: .

    - name: Test
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --event-handlers console_cohesion+
      working-directory: .
