name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.2.4
      with:
        required-ros-distributions: humble

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y python3-colcon-common-extensions
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build package
      run: colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: colcon test --event-handlers console_cohesion+
      
    - name: Test result reporting
      run: colcon test-result --verbose