name: ROS 2 CI
on:
  push:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./request_handler/requirements.txt
          pip install boto3
      - name: Test with unittest
        run: |
          cd request_handler
          python -m unittest discover -s ./test -p 'test_*.py'
