name: ROS 2 CI
on:
  push:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install ROS 2 dependencies
        run: |
          sudo apt update
          sudo apt install ros-foxy-rclpy
      - name: Test with unittest
        run: |
          cd ros_SM
          python -m unittest -v 'test_sm.py'
